[package]
name = "cli"
version = "0.1.0"
authors = ["Navid <yaa110@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.4.12"
common = { path = "../common" }
gumdrop = "0.5.0"
hex = "0.3.2"
