[package]
name = "server"
version = "0.1.0"
authors = ["Navid <yaa110@gmail.com>"]
edition = "2018"
publish = false

[[bin]]
name = "cb-server"
path = "src/main.rs"

[dependencies]
bytes = "0.4.12"
env_logger = "0.6.1"
gumdrop = "0.5.0"
log = "0.4.6"
tokio = "0.1.19"
