[package]
name = "common"
version = "0.1.0"
authors = ["Navid <yaa110@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
bincode = "1.1.3"
bytes = "0.4.12"
lazy_static = "1.3.0"
serde = "1.0.90"
serde_derive = "1.0.90"
